site_name: YARL - Yet Another RogueLike
repo_url: https://github.com/MalayAgr/yarl
edit_uri: "blob/master/docs/"

theme:
  name: material
  features:
  - announce.dismiss
  - content.code.copy
  - content.tooltips
  - navigation.footer
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - search.highlight
  - search.suggest
  - toc.follow
  - toc.integrate
  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    accent: purple
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    toggle:
      icon: material/weather-night
      name: Switch to light mode

markdown_extensions:
- attr_list
- smarty
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
- md_in_html
- admonition
- def_list
- meta
- toc:
    baselevel: 1
    permalink: true
- pymdownx.keys
- pymdownx.tabbed:
    alternate_style: true
    slugify: !!python/object/apply:pymdownx.slugs.slugify
      kwds:
        case: lower
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
    pygments_lang_class: true
- pymdownx.details
- pymdownx.magiclink
- pymdownx.inlinehilite
- pymdownx.superfences
- pymdownx.snippets


plugins:
- search: {}
- social:
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.txt
- section-index:
- mkdocstrings:
    custom_templates: docs/_templates
    default_handler: python
    handlers:
      python:
        import:
          - https://docs.python.org/3/objects.inv
          - https://python-tcod.readthedocs.io/en/stable/objects.inv
          - https://numpy.org/doc/stable/objects.inv
        options:
          members_order: source
          show_signature_annotations: false
          separate_signature: true
          merge_init_into_class: true
          docstring_options:
            ignore_init_summary: true
          show_source: false
          filters:
            - "!^_"
            - "^__init__$"
            - "!^can_replace$"
          line-length: 88


watch:
  - mkdocs.yml
  - src/yarl/

extra_css:
  - stylesheets/custom.css


nav:
- Introduction: index.md
- Download and Install: download-install.md
- Code Reference: reference/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MalayAgr
      name: Malay Agarwal on GitHub
    - icon: fontawesome/brands/github
      link: https://github.com/jashAtGit
      name: Jashwanth Sai on GitHub
copyright: Copyright &copy; Malay Agarwal, Jashwanth Sai
