[tool.poetry]
name = "yarl"
version = "0.1.0"
description = ""
authors = ["Malay Agarwal <malay.agarwal261016@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
