name: Test

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install --with dev
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      - name: Format code using black
        run: |
          source $VENV
          black .
      - name: Test with pytest
        run: |
          source $VENV
          pytest
