name: Test

on:
  pull_request:
    branches:
      - main

defaults:
      run:
        shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          architecture: x64
          cache: "poetry"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: poetry install
      - name: Format code using black
        run: |
          source $VENV
          black .
      - name: Test with pytest
        run: |
          source $VENV
          pytest -v --cov=yarl/ --cov-report=xml:./coverage.xml --cov-report term-missing
